trainer:
  name: lipizzaner_gan
  n_iterations: 1000 #200
  calculate_net_weights_dist: True
  # independent_probability, exact_proportion
  mixture_generator_samples_mode: exact_proportion
  params:
    population_size: 1
    tournament_size: 2
    n_replacements: 1
    default_adam_learning_rate: 0.0002
    # Hyperparameter mutation
    alpha: 0.0001
    mutation_probability: 0.5
    discriminator_skip_each_nth_step: 1
    mixture_sigma: 0.01
    enable_selection: True
    score:
      enabled: True
      type: fid
      score_sample_size: 300
      cuda: True
    fitness:
      fitness_sample_size: 300
      fitness_mode: average    # worse, best, average
dataloader:
  dataset_name: covidqu
  use_batch: True
  batch_size: 128
  n_batches: 0
  shuffle: True
  subset_file: Test_6_nested/6_nested_split_0.2_gan.pkl
  augment: False
network:
  name: convolutional_grayscale128x128
  loss: bceloss
  history: True
master:
  calculate_score: True
  # Same amount of data as original CIFAR contains
  score_sample_size: 300
  cuda: True
general: !include general.yml